<a href="https://colab.research.google.com/github/Savasiswetha/batch-30/blob/main/lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
list1=[1,2,3]
arr1=np.array (list1)
arr1

array([1, 2, 3])

In [ ]:
type(list1)

list

In [ ]:
import numpy as np
list2=[3,4,5]
arr2=np.array(list2)
arr2

array([3, 4, 5])

In [ ]:
print(arr1+arr2)


[4 6 8]


In [ ]:
arr3=arr1=arr2
arr3


array([3, 4, 5])

In [ ]:
print("array1 divided by array2=",arr2/arr1)

array1 divided by array2= [1. 1. 1.]


In [ ]:
print("array1 mult by array2=",arr1*arr2)

array1 mult by array2= [ 9 16 25]


In [ ]:
print("array1 mult by array2=",arr1*arr2)

array1 mult by array2= [ 9 16 25]


sine: [ 0.14112001 -0.7568025  -0.95892427]
natural log: [1.09861229 1.38629436 1.60943791]
